services:
  postgres:
    image: postgres:15-alpine
    container_name: palety-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: palety_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: palety-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: palety-api
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/palety_db
      - PORT=4000
    depends_on:
      - postgres
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: palety-web
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
